on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
      
    - uses: actions/upload-artifact@v3
      with:
        name: server
        path: target/release/mrt-flightradar-server
