on:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: RUST_LOG=trace cargo run --package mrt-flightradar-data-updater
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update raw data
